let
    Source = List.Dates,
    InvokeDates = Source(#date(2019, 01, 01), Duration.Days(DateTime.Date(DateTime.FixedLocalNow())- #date(2019, 01, 01))+1, #duration(1, 0, 0, 0)),
    #"List to table" = Table.FromList(InvokeDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    Date = Table.RenameColumns(#"List to table",{{"Column1", "Date"}}),
    Day = Table.AddColumn(Date, "DayNo", each Text.PadStart(Number.ToText(Date.Day([Date])),2,"0")),
    ShortWeek = Table.AddColumn(Day, "Day Name", each Date.ToText([Date],"ddd","en-US")),
    #"Month No" = Table.AddColumn(ShortWeek, "Month No", each Date.Month([Date])),
    MonthName = Table.AddColumn(#"Month No", "Month Name", each Date.ToText([Date],"MMM","en-us")),
    Quarter = Table.AddColumn(MonthName, "Quarter No", each Date.QuarterOfYear([Date])),
    ExtractYear = Table.AddColumn(Quarter, "Year", each Date.Year([Date])),
    MonthNumber_Year = Table.AddColumn(ExtractYear, "Month_Year", each Text.Combine({Date.ToText([Date], "%M"), "_", Date.ToText([Date], "yyyy")}), type text),
    #"Year Quarter Added" = Table.AddColumn(MonthNumber_Year, "Year-Quarter", each Number.ToText([Year]) & "Q"& Number.ToText([Quarter No],"00")),
    #"Change type to text" = Table.TransformColumnTypes(#"Year Quarter Added",{{"Year", Int64.Type}, {"Date", type date}, {"Month No", Int64.Type}, {"Day Name", type text}, {"Month Name", type text}, {"Quarter No", Int64.Type}, {"Year-Quarter", type text},   {"DayNo", type text} }),
    #"Sort DayName" = Table.AddColumn(#"Change type to text", "DayName", each Date.DayOfWeek([Date],1)),
    YearMonth = Table.AddColumn(#"Sort DayName", "YearMonth", each Number.ToText([Year])&Text.PadStart(Number.ToText([Month No]),2,"0")),
    YearQuarter = Table.AddColumn(YearMonth, "YearQuarter", each Number.ToText([Year])&Text.PadStart(Number.ToText([Quarter No]),2,"0")),
    #"Changed Type" = Table.TransformColumnTypes(YearQuarter,{{"DayName", Int64.Type}, {"YearMonth", type text}, {"YearQuarter", type text}})
in
    #"Changed Type"